config/routes.rb
Rails.application.routes.draw do
  get 'pages/myMentees'

  resources :mentees

  get 'pages/profile'

  get 'pages/mentor'

  get 'pages/location'

  get 'pages/categories'

  get 'pages/myMentors'

  get 'pages/about'

  get 'mentors/index'

  get 'mentors/show'

  get 'mentors/edit'

  get 'mentors/new'

  get 'mentees/index'

  get 'mentees/show'

  get 'mentees/edit'

  get 'mentees/new'

  resources :mentors
  get 'pages/alice'
  root 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mentee.rb
class Mentee < ApplicationRecord
end

app/models/mentor.rb
class Mentor < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/mentees_controller.rb
class MenteesController < ApplicationController
  before_action :set_mentee, only: [:show, :edit, :update, :destroy]

  # GET /mentees
  # GET /mentees.json
  def index
    @mentees = Mentee.all
  end

  # GET /mentees/1
  # GET /mentees/1.json
  def show
  end

  # GET /mentees/new
  def new
    @mentee = Mentee.new
  end

  # GET /mentees/1/edit
  def edit
  end

  # POST /mentees
  # POST /mentees.json
  def create
    @mentee = Mentee.new(mentee_params)

    respond_to do |format|
      if @mentee.save
        format.html { redirect_to @mentee, notice: 'Mentee was successfully created.' }
        format.json { render :show, status: :created, location: @mentee }
      else
        format.html { render :new }
        format.json { render json: @mentee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentees/1
  # PATCH/PUT /mentees/1.json
  def update
    respond_to do |format|
      if @mentee.update(mentee_params)
        format.html { redirect_to @mentee, notice: 'Mentee was successfully updated.' }
        format.json { render :show, status: :ok, location: @mentee }
      else
        format.html { render :edit }
        format.json { render json: @mentee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentees/1
  # DELETE /mentees/1.json
  def destroy
    @mentee.destroy
    respond_to do |format|
      format.html { redirect_to mentees_url, notice: 'Mentee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentee
      @mentee = Mentee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mentee_params
      params.require(:mentee).permit(:first_name, :last_name, :university, :email, :skills)
    end
end

app/controllers/mentors_controller.rb
class MentorsController < ApplicationController
  before_action :set_mentor, only: [:show, :edit, :update, :destroy]

  # GET /mentors
  # GET /mentors.json
  def index
    @mentors = Mentor.all
  end

  # GET /mentors/1
  # GET /mentors/1.json
  def show
  end

  # GET /mentors/new
  def new
    @mentor = Mentor.new
  end

  # GET /mentors/1/edit
  def edit
  end

  # POST /mentors
  # POST /mentors.json
  def create
    @mentor = Mentor.new(mentor_params)

    respond_to do |format|
      if @mentor.save
        format.html { redirect_to @mentor, notice: 'Mentor was successfully created.' }
        format.json { render :show, status: :created, location: @mentor }
      else
        format.html { render :new }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mentors/1
  # PATCH/PUT /mentors/1.json
  def update
    respond_to do |format|
      if @mentor.update(mentor_params)
        format.html { redirect_to @mentor, notice: 'Mentor was successfully updated.' }
        format.json { render :show, status: :ok, location: @mentor }
      else
        format.html { render :edit }
        format.json { render json: @mentor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mentors/1
  # DELETE /mentors/1.json
  def destroy
    @mentor.destroy
    respond_to do |format|
      format.html { redirect_to mentors_url, notice: 'Mentor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mentor
      @mentor = Mentor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mentor_params
      params.require(:mentor).permit(:first_name, :last_name, :email, :skills)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def profile
  end

  def mentor
  end

  def location
  end

  def categories
  end

  def myMentors
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mentees_helper.rb
module MenteesHelper
end

app/helpers/mentors_helper.rb
module MentorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Manatee | Find Your Mentor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, shrink-to-fit=no, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  </head>

  <body>

  <div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand"><%= link_to 'Manatee', pages_about_path %></li>
            <li><%= link_to 'About', pages_about_path %></li>
            <li><%= link_to 'Profile', pages_profile_path %></li>
            <li>
                <%= link_to 'Location', pages_location_path %>
                <%= link_to 'Categories', pages_categories_path %>
            </li>
            <li><%= link_to 'Mentors', pages_myMentors_path %></li>

            <li><%= link_to 'My Mentors', mentors_path %></li>

        </ul>
    </div>
 
    <!-- /#sidebar-wrapper -->

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <a href="#menu-toggle" class="btn btn-default" id="menu-toggle">MANATEE</a>
                </div>
            </div>
        </div>
    </div>

   </div>

    <div id="page-content-wrapper">
        <div class="container-fluid">
			<%= yield %>
		</div>
	</div>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>

  </body>
</html>

app/views/mentees/_form.html.erb
<%= form_with(model: mentee, local: true) do |form| %>
  <% if mentee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mentee.errors.count, "error") %> prohibited this mentee from being saved:</h2>

      <ul>
      <% mentee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :mentee_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :mentee_last_name %>
  </div>

  <div class="field">
    <%= form.label :university %>
    <%= form.text_field :university, id: :mentee_university %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :mentee_email %>
  </div>

  <div class="field">
    <%= form.label :skills %>
    <%= form.text_area :skills, id: :mentee_skills %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mentees/edit.html.erb
<h1>Editing Mentee</h1>

<%= render 'form', mentee: @mentee %>

<%= link_to 'Show', @mentee %> |
<%= link_to 'Back', mentees_path %>

app/views/mentees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mentees</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>University</th>
      <th>Email</th>
      <th>Skills</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mentees.each do |mentee| %>
      <tr>
        <td><%= mentee.first_name %></td>
        <td><%= mentee.last_name %></td>
        <td><%= mentee.university %></td>
        <td><%= mentee.email %></td>
        <td><%= mentee.skills %></td>
        <td><%= link_to 'Show', mentee %></td>
        <td><%= link_to 'Edit', edit_mentee_path(mentee) %></td>
        <td><%= link_to 'Destroy', mentee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mentee', new_mentee_path %>

app/views/mentees/new.html.erb
<h1>New Mentee</h1>

<%= render 'form', mentee: @mentee %>

<%= link_to 'Back', mentees_path %>

app/views/mentees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @mentee.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @mentee.last_name %>
</p>

<p>
  <strong>University:</strong>
  <%= @mentee.university %>
</p>

<p>
  <strong>Email:</strong>
  <%= @mentee.email %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @mentee.skills %>
</p>

<%= link_to 'Edit', edit_mentee_path(@mentee) %> |
<%= link_to 'Back', mentees_path %>

app/views/mentors/_form.html.erb
<%= form_with(model: mentor, local: true) do |form| %>
  <% if mentor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mentor.errors.count, "error") %> prohibited this mentor from being saved:</h2>

      <ul>
      <% mentor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :mentor_first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :mentor_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :mentor_email %>
  </div>

  <div class="field">
    <%= form.label :skills %>
    <%= form.text_area :skills, id: :mentor_skills %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mentors/edit.html.erb
<h1>Editing Mentor</h1>

<%= render 'form', mentor: @mentor %>

<%= link_to 'Show', @mentor %> |
<%= link_to 'Back', mentors_path %>

app/views/mentors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mentors</h1>

<table class="table">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th>Skills</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mentors.each do |mentor| %>
      <tr>
        <td><%= mentor.first_name %></td>
        <td><%= mentor.last_name %></td>
        <td><%= mentor.email %></td>
        <td><%= mentor.skills %></td>

      <!--
        <td><%= link_to 'Show', mentor %></td>
        <td><%= link_to 'Edit', edit_mentor_path(mentor) %></td>
        <td><%= link_to 'Destroy', mentor, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mentor', new_mentor_path %>

app/views/mentors/new.html.erb
<h1>New Mentor</h1>

<%= render 'form', mentor: @mentor %>

<%= link_to 'Back', mentors_path %>

app/views/mentors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @mentor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @mentor.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @mentor.email %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @mentor.skills %>
</p>

<%= link_to 'Edit', edit_mentor_path(@mentor) %> |
<%= link_to 'Back', mentors_path %>

app/views/pages/about.html.erb
<!-- Mission Statement -->

<div id="page-content-wrapper">
    <div class="container-fluid">
	    <div class="jumbotron">
	    	<h1>Welcome to Manatee</h1>
	    	<p>Manatee is a web app that connects mentors with mentees. It's a free service so anyone can join. You can build meaningful connections and explore potential educational and career options. Having a mentor who can offer guidance can make it easier for you to make career and education-related choices. In turn, you can take on a mentee for something else that you may have experience in.</p>
	    	<p>
	    	  <div class="row">
	    	    <div class="col-lg-6">

		          <span class="btn btn-lg btn-primary register_buttons" role="button">
		          	<%= link_to 'Register as Mentee', mentees_new_path %>

		          </span>
		        </div>
		        <div class="col-lg-6">
		          <span class="btn btn-lg btn-primary register_buttons" role="button">
		          	<%= link_to 'Register as Mentor', mentors_new_path %>
		          </span>
		        </div>
	          </div>
	          <div class="row">
	    	    <div class="col-lg-6">
		          <span class="btn btn-lg btn-primary register_buttons" role="button">
		          	<%= link_to 'Sign in as Mentee', pages_profile_path %>
		          </span>
		        </div>
		        <div class="col-lg-6">
		          <span class="btn btn-lg btn-primary register_buttons" role="button">
		          	<%= link_to 'Sign in as Mentor', pages_profile_path %>
		          </span>
		        </div>
	          </div>
	        </p>
		</div>
	</div>
</div>

<!-- Mentor Mentee Benefits -->

app/views/pages/categories.html.erb
<h1>Pages#categories</h1>
<p>Find me in app/views/pages/categories.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/location.html.erb
<h1>Pages#location</h1>
<p>Find me in app/views/pages/location.html.erb</p>

app/views/pages/myMentees.html.erb
<h1>Pages#myMentees</h1>
<p>Find me in app/views/pages/myMentees.html.erb</p>

app/views/pages/myMentors.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @mentor.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @mentor.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @mentor.email %>
</p>

<p>
  <strong>Skills:</strong>
  <%= @mentor.skills %>
</p>

app/views/pages/profile.html.erb
<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="jumbotron">
            <div class="row">
                <div class="col-sm-6">
                    <img src="https://www.capsule8.io/img/headshots/brandon-edwards.png">
                </div>
                <div class="col-sm-6">
                    <h1>Brandon Edwards</h1>
                    <h2>NYU Tandon University</h2>
                    <p>Brandon was previously VP of Threat Labs at BAE Systems, through its successful acquisition of SilverSky. There, he led the development of their cloud-based, zero-day prevention product.<br>
                    Brandon was previously VP of Threat Labs at BAE Systems, through its successful acquisition of SilverSky. There, he led the development of their cloud-based, zero-day prevention product.
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>